source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

target 'universes-mobile' do
  pod 'ExpoKit',
    :git => "http://github.com/expo/expo.git",
    :tag => "ios/2.10.2",
    :subspecs => [
      "Core"
    ],
    :inhibit_warnings => true
  pod 'EXAdsAdMob',
    :path => ".expo-ads-admob/ios"
  pod 'EXSegment',
    :path => ".expo-analytics-segment/ios"
  pod 'EXAppAuth',
    :path => ".expo-app-auth/ios"
  pod 'EXAppLoaderProvider',
    :path => ".expo-app-loader-provider/ios"
  pod 'EXBackgroundFetch',
    :path => ".expo-background-fetch/ios"
  pod 'EXBarCodeScanner',
    :path => ".expo-barcode-scanner/ios"
  pod 'EXBarCodeScannerInterface',
    :path => ".expo-barcode-scanner-interface/ios"
  pod 'EXCamera',
    :path => ".expo-camera/ios"
  pod 'EXCameraInterface',
    :path => ".expo-camera-interface/ios"
  pod 'EXConstants',
    :path => ".expo-constants/ios"
  pod 'EXConstantsInterface',
    :path => ".expo-constants-interface/ios"
  pod 'EXContacts',
    :path => ".expo-contacts/ios"
  pod 'EXCore',
    :path => ".expo-core/ios"
  pod 'EXErrors',
    :path => ".expo-errors/ios"
  pod 'EXFaceDetectorInterface',
    :path => ".expo-face-detector-interface/ios"
  pod 'EXFileSystem',
    :path => ".expo-file-system/ios"
  pod 'EXFileSystemInterface',
    :path => ".expo-file-system-interface/ios"
  pod 'EXFont',
    :path => ".expo-font/ios"
  pod 'EXFontInterface',
    :path => ".expo-font-interface/ios"
  pod 'EXGL',
    :path => ".expo-gl/ios"
  pod 'EXGL-CPP',
    :path => ".expo-gl-cpp/cpp"
  pod 'EXGoogleSignIn',
    :path => ".expo-google-sign-in/ios"
  pod 'EXImageLoaderInterface',
    :path => ".expo-image-loader-interface/ios"
  pod 'EXLocalAuthentication',
    :path => ".expo-local-authentication/ios"
  pod 'EXLocalization',
    :path => ".expo-localization/ios"
  pod 'EXLocation',
    :path => ".expo-location/ios"
  pod 'EXMediaLibrary',
    :path => ".expo-media-library/ios"
  pod 'EXPermissions',
    :path => ".expo-permissions/ios"
  pod 'EXPermissionsInterface',
    :path => ".expo-permissions-interface/ios"
  pod 'EXPrint',
    :path => ".expo-print/ios"
  pod 'EXReactNativeAdapter',
    :path => ".expo-react-native-adapter/ios"
  pod 'EXSensors',
    :path => ".expo-sensors/ios"
  pod 'EXSensorsInterface',
    :path => ".expo-sensors-interface/ios"
  pod 'EXSMS',
    :path => ".expo-sms/ios"
  pod 'EXTaskManager',
    :path => ".expo-task-manager/ios"
  pod 'EXTaskManagerInterface',
    :path => ".expo-task-manager-interface/ios"

  pod 'React',
    :path => ".react-native",
    :inhibit_warnings => true,
    :subspecs => [
      "Core",
      "ART",
      "RCTActionSheet",
      "RCTAnimation",
      "RCTCameraRoll",
      "RCTGeolocation",
      "RCTImage",
      "RCTNetwork",
      "RCTText",
      "RCTVibration",
      "RCTWebSocket",
      "DevSupport",
      "CxxBridge"
    ]
  pod 'yoga',
    :path => ".react-native/ReactCommon/yoga",
    :inhibit_warnings => true
  pod 'DoubleConversion',
    :podspec => ".react-native/third-party-podspecs/DoubleConversion.podspec",
    :inhibit_warnings => true
  pod 'Folly',
    :podspec => ".react-native/third-party-podspecs/Folly.podspec",
    :inhibit_warnings => true
  pod 'glog',
    :podspec => ".react-native/third-party-podspecs/glog.podspec",
    :inhibit_warnings => true


  pod 'react-native-splash-screen', :path => '.react-native-splash-screen'

  pod 'RNVectorIcons', :path => '.react-native-vector-icons'



  pod 'TouchID', :path => '.react-native-touch-id'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  post_install do |installer|
    installer.pods_project.main_group.tab_width = '2';
    installer.pods_project.main_group.indent_width = '2';

    installer.pod_targets.each do |target|

    if target.pod_name == 'ExpoKit'
      target.native_target.build_configurations.each do |config|
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'EX_DETACHED=1'
        
        # needed for GoogleMaps 2.x
        config.build_settings['FRAMEWORK_SEARCH_PATHS'] ||= []
        config.build_settings['FRAMEWORK_SEARCH_PATHS'] << '${PODS_ROOT}/GoogleMaps/Base/Frameworks'
        config.build_settings['FRAMEWORK_SEARCH_PATHS'] << '${PODS_ROOT}/GoogleMaps/Maps/Frameworks'
      end
    end


    if ['Amplitude-iOS','Analytics','AppAuth','Branch','CocoaLumberjack','FBSDKCoreKit','FBSDKLoginKit','FBSDKShareKit','GPUImage','JKBigInteger2'].include? target.pod_name
      target.native_target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
      end
    end
    # Can't specify this in the React podspec because we need
    # to use those podspecs for detached projects which don't reference ExponentCPP.
    if target.pod_name.start_with?('React')
      target.native_target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
        config.build_settings['HEADER_SEARCH_PATHS'] ||= ['$(inherited)']
      end
    end
    # Build React Native with RCT_DEV enabled and RCT_ENABLE_INSPECTOR and
    # RCT_ENABLE_PACKAGER_CONNECTION disabled
    next unless target.pod_name == 'React'
    target.native_target.build_configurations.each do |config|
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'RCT_DEV=1'
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'RCT_ENABLE_INSPECTOR=0'
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'ENABLE_PACKAGER_CONNECTION=0'
    end

    end
  end
end
